// Platform administration: accounts, companies, plans, campaigns, automations, outbox and leads.
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const P={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m18 0v-2a4 4 0 0 0-3-3.87M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8m8 0a4 4 0 0 1 0 8',building:'M3 21V7l9-4 9 4v14M8 21v-6h8v6M8 9v2m8-2v2M1 21h22',send:'M22 2 11 13 M22 2l-7 20-4-9-9-4z',bolt:'M13 2 3 14h9l-1 8 10-12h-9z',mail:'M3 5h18v14H3z M3 6l9 7 9-7',inbox:'M22 12h-6l-2 3h-4l-2-3H2 M5 5h14l3 7v7H2v-7z',back:'M19 12H5 M11 6l-6 6 6 6',download:'M12 3v12 M7 10l5 5 5-5 M4 21h16',close:'M18 6 6 18M6 6l12 12',check:'m5 12 4 4L19 6',search:'M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14z M21 21l-4.3-4.3',eye:'M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12z M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z',trend:'M3 17l6-6 4 4 8-8 M14 7h7v7',edit:'M12 20h9 M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z',phone:'M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.4 1.8.7 2.7a2 2 0 0 1-.5 2.1L8 9.8a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.8.6 2.7.7a2 2 0 0 1 1.7 2z',external:'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6 M15 3h6v6 M10 14 21 3',trash:'M3 6h18 M8 6V4h8v2 M19 6l-1 14H6L5 6'};
const icon=n=>`<svg class="icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${P[n]}"/></svg>`;
const api=async(url,opt={})=>{const r=await fetch(url,opt);const t=r.headers.get('content-type')||'';const body=t.includes('json')?await r.json():await r.text();if(!r.ok)throw Error(body.error||'İstek başarısız.');return body;};
const post=(url,b)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b||{})});
const date=d=>d?new Date(d).toLocaleDateString('tr-TR',{day:'numeric',month:'short',year:'numeric'}):'—';
const dateTime=d=>d?new Date(d).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const planName={trial:'Deneme',ekip:'Ekip',buro:'Büro',kurumsal:'Kurumsal'};
const toast=(text,error=false)=>{const el=document.createElement('div');el.className='toast'+(error?' error':'');el.innerHTML=icon(error?'close':'check')+`<span>${esc(text)}</span>`;$('#toasts').append(el);setTimeout(()=>el.remove(),4500);};
const modal=(title,html,wide)=>{const m=$('#modal');m.className=wide?'wide':'';m.innerHTML=`<div class="modal-head"><div><h2>${esc(title)}</h2></div><button class="icon-button" data-close aria-label="Kapat">${icon('close')}</button></div>${html}`;if(!m.open)m.showModal();};
const heading=(title,sub,actions='')=>`<div class="page-heading"><div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="heading-actions">${actions}</div></div>`;
const views={sales:['Satış','trend'],leads:['Talepler','mail'],site:['Site içeriği','edit'],overview:['Platform','grid'],accounts:['Kullanıcılar','users'],spaces:['Şirketler','building'],campaigns:['Kampanyalar','send'],automations:['Otomasyonlar','bolt'],outbox:['E-posta kutusu','inbox']};
const LEAD_STATUS={new:'Yeni',contacted:'İletişimde',demo:'Demo yapıldı',won:'Kazanıldı',lost:'Kaybedildi'};
let range=30,leadFilter='all',leadQuery='';
const pct=(a,b)=>b?Math.round(a/b*1000)/10:0,num=n=>Number(n||0).toLocaleString('tr-TR'),tl=n=>Number(n||0).toLocaleString('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0});
let view=location.hash.slice(1)||'sales',me=null,cache={},query='',filter='all';
try{const t=localStorage.getItem('buros-theme');document.documentElement.dataset.theme=t==='gece'?'gece':'orman';}catch{}

function chrome(){
 $('#sidebar').innerHTML=`<div class="sb-top"><a class="brand" href="/app" aria-label="Uygulamaya dön"><img src="/brand/logo.svg" alt="bürOS" height="28"></a></div><div class="admin-tag">Platform yönetimi</div><nav>${Object.entries(views).map(([k,[n,ic]])=>`<button class="nav-item ${view===k?'active':''}" data-view="${k}">${icon(ic)}<span>${n}</span></button>`).join('')}</nav><div class="sidebar-end"><a class="nav-item" href="/app">${icon('back')}<span>Uygulamaya dön</span></a><div class="profile"><span class="avatar">${esc((me.name||'').split(' ').map(x=>x[0]).slice(0,2).join(''))}</span><span class="profile-text"><b>${esc(me.name)}</b><small>${esc(me.email)}</small></span></div></div>`;
 $('#header').innerHTML=`<div class="breadcrumb"><b>${views[view][0]}</b></div><div></div><div class="header-tools"><span class="sync" data-state="saved"><span class="sync-icon"></span><span>Canlı veri</span></span></div>`;
}
async function load(key,url){cache[key]=await api(url);return cache[key];}
async function render(){chrome();const main=$('#main');main.innerHTML='<div class="loading"><small>Yükleniyor…</small></div>';try{main.innerHTML=await renderers[view]();}catch(e){main.innerHTML=`<div class="empty"><h3>Veri alınamadı</h3><p>${esc(e.message)}</p></div>`;}}
const kpi=(label,value,sub='',cls='')=>`<div class="kpi ${cls}"><span class="kpi-label">${label}</span><strong>${value}</strong><small>${sub}</small></div>`;
const table=(head,rows,empty='Kayıt yok.')=>`<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}"><p class="card-empty">${empty}</p></td></tr>`}</tbody></table></div>`;
const trialText=s=>s.plan!=='trial'?`<span class="state-text done">${planName[s.plan]}</span>`:s.expired?'<span class="state-text late">Deneme bitti</span>':`<span class="state-text">Deneme · ${s.daysLeft} gün</span>`;

// Daily bar chart with readable axis labels and hover titles.
function dayChart(days,key,label,cls=''){const W=760,H=200,max=Math.max(1,...days.map(d=>d[key])),bw=W/days.length,step=Math.ceil(days.length/8),ticks=[0,.5,1].map(f=>Math.round(max*f));
 return `<svg class="workload sales-chart ${cls}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${label}">${ticks.map(t=>`<line class="wl-grid" x1="0" x2="${W}" y1="${H-22-(t/max)*(H-44)}" y2="${H-22-(t/max)*(H-44)}"/><text class="wl-axis" x="2" y="${H-26-(t/max)*(H-44)}">${num(t)}</text>`).join('')}${days.map((d,i)=>{const h=d[key]/max*(H-44);return `<g class="wl-bar"><rect class="wl-hit" x="${i*bw}" y="0" width="${bw}" height="${H-22}"/>${h?`<rect class="sales-bar" x="${i*bw+bw*.18}" y="${H-22-h}" width="${bw*.64}" height="${h}" rx="2"/>`:''}${i%step===0?`<text class="wl-axis" x="${i*bw+bw/2}" y="${H-6}" text-anchor="middle">${new Date(d.date).toLocaleDateString('tr-TR',{day:'numeric',month:'short'})}</text>`:''}<title>${date(d.date)}: ${num(d[key])} ${label.toLocaleLowerCase('tr')}</title></g>`;}).join('')}</svg>`;}
const statusPill=st=>`<span class="lead-status s-${st||'new'}">${LEAD_STATUS[st||'new']}</span>`;
function leadDetail(l){const notes=(l.notes||[]).slice().reverse(),hist=(l.history||[]).slice().reverse();
 return `<div class="lead-detail"><div class="lead-facts"><div><small>E-posta</small><a href="mailto:${esc(l.email)}">${esc(l.email)}</a></div><div><small>Telefon</small>${l.phone?`<a href="tel:${esc(l.phone.replace(/[^+0-9]/g,''))}">${esc(l.phone)}</a>`:'—'}</div><div><small>Firma</small>${esc(l.company||'—')}</div><div><small>Ekip</small>${esc(l.teamSize||'—')}</div><div><small>Plan</small>${planName[l.plan]||esc(l.plan||'—')}</div><div><small>Geliş</small>${dateTime(l.at)}${l.repeat?` · ${l.repeat+1}. talep`:''}</div></div>${l.message?`<blockquote class="lead-msg">${esc(l.message)}</blockquote>`:''}
 <form id="leadForm" data-id="${l.id}" class="lead-form"><div class="form-grid"><label class="field"><span>Durum</span><select name="status">${Object.entries(LEAD_STATUS).map(([k,n])=>`<option value="${k}" ${(l.status||'new')===k?'selected':''}>${n}</option>`).join('')}</select></label><label class="field"><span>Sonraki takip</span><input type="date" name="nextAt" value="${esc(l.nextAt||'')}"></label><label class="field"><span>Tahmini aylık değer (₺)</span><input type="number" name="value" min="0" step="50" value="${l.value||''}" placeholder="0"></label></div><label class="field"><span>Not ekle</span><textarea name="note" rows="3" placeholder="Görüşme notu, itirazlar, sonraki adım…"></textarea></label><div class="button-row"><button type="button" class="lead-delete" data-lead-delete="${l.id}">${icon('trash')} Talebi sil</button><button class="primary">Kaydet</button></div></form>
 ${notes.length||hist.length?`<div class="lead-timeline"><h3>Geçmiş</h3>${[...notes.map(n=>({...n,kind:'note'})),...hist.map(h=>({...h,kind:'status'}))].sort((a,b)=>b.at.localeCompare(a.at)).map(x=>`<div class="tl-item ${x.kind}"><small>${dateTime(x.at)} · ${esc(x.by||'')}</small>${x.kind==='note'?`<p>${esc(x.text)}</p>`:`<p>Durum: ${LEAD_STATUS[x.status]}</p>`}</div>`).join('')}</div>`:''}</div>`;}
const renderers={
 async sales(){const d=await api('/api/admin/sales?days='+range),t=d.totals,L=cache.leads=await api('/api/admin/leads');const steps=[['Ziyaret',t.visits],['Ücretsiz dene tıklaması',t.signupClicks],['Demo formuna başlayan',t.demoStarts],['Demo talebi',t.leads],['Hesap açan',t.signups],['Çalışma alanı kuran',t.spaces]],top=Math.max(1,...steps.map(x=>x[1]));
  const today=new Date().toISOString().slice(0,10),due=L.filter(l=>l.nextAt&&l.nextAt<=today&&!['won','lost'].includes(l.status||'new'));
  return heading('Satış',`Son ${range} gün · ziyaretler çerezsiz ve kimliksiz sayılır`,`<div class="segmented" role="group" aria-label="Dönem">${[7,30,90].map(n=>`<button class="${range===n?'on':''}" data-range="${n}">${n} gün</button>`).join('')}</div><a class="secondary" href="/" target="_blank" rel="noopener">${icon('external')} Siteyi aç</a>`)
  +`<section class="kpis">${kpi('Ziyaret',num(t.visits),`${num(t.signupClicks)} ücretsiz dene tıklaması`)}${kpi('Demo talebi',num(t.leads),`Ziyaretçilerin %${pct(t.leads,t.visits)}'i`)}${kpi('Yeni hesap',num(t.signups),`Ziyaretçilerin %${pct(t.signups,t.visits)}'i`)}${kpi('Ücretli müşteri',num(d.paid),`${num(d.trials)} denemede · ${num(d.expired)} süresi dolmuş`)}</section>`
  +`<div class="dash-grid"><section class="card span-7"><div class="card-head"><h2>Satış hunisi</h2><span class="card-sub">Her adımın bir öncekine oranı</span></div><div class="funnel">${steps.map(([n,v],i)=>`<div class="funnel-row"><span class="funnel-name">${n}</span><span class="funnel-bar"><i style="width:${Math.max(v?2:0,v/top*100)}%"></i></span><b>${num(v)}</b><small>${i?`%${pct(v,steps[i-1][1])}`:''}</small></div>`).join('')}</div></section>
  <section class="card span-5"><div class="card-head"><h2>Fırsat hattı</h2><button class="text-button" data-view="leads">Tüm talepler</button></div><div class="pipe-cols">${Object.entries(LEAD_STATUS).map(([k,n])=>`<button class="pipe-col s-${k}" data-lead-filter="${k}"><b>${num(d.status[k])}</b><span>${n}</span></button>`).join('')}</div><div class="pipe-sum"><div><small>Açık fırsat değeri</small><b>${tl(d.pipelineValue)}<em>/ay</em></b></div><div><small>Kazanılan</small><b>${tl(d.wonValue)}<em>/ay</em></b></div><div class="${d.followUps?'due':''}"><small>Takibi gelen</small><b>${num(d.followUps)}</b></div></div></section>
  <section class="card span-8"><div class="card-head"><h2>Günlük ziyaret</h2><span class="card-sub">Sayfanın açılması, oturum başına bir kez</span></div>${dayChart(d.days,'visits','Ziyaret','visits')}</section>
  <section class="card span-4"><div class="card-head"><h2>Trafik kaynakları</h2><span class="card-sub">Yönlendiren site</span></div>${d.refs.length?`<div class="fin-bars">${d.refs.map(([h,c])=>`<div><span>${esc(h)}</span><span class="bar"><i style="width:${c/d.refs[0][1]*100}%"></i></span><b>${num(c)}</b></div>`).join('')}</div>`:'<p class="card-empty">Henüz yönlendirme yok. Doğrudan girişler burada sayılmaz.</p>'}</section>
  <section class="card span-6"><div class="card-head"><h2>Günlük demo talebi</h2></div>${dayChart(d.days,'leads','Demo talebi','leads')}</section>
  <section class="card span-6"><div class="card-head"><h2>Günlük yeni hesap</h2></div>${dayChart(d.days,'signups','Yeni hesap','signups')}</section>
  <section class="card span-12"><div class="card-head"><h2>${due.length?`Bugün takip edilecekler <span class="count">${due.length}</span>`:'Son talepler'}</h2><button class="text-button" data-view="leads">Tümü</button></div>${table(['Kişi','Firma','Plan','Durum','Takip','Geliş'],(due.length?due:L.slice(0,6)).map(l=>`<tr class="clickable" data-lead-open="${l.id}"><td><b>${esc(l.name||l.email)}</b><small>${esc(l.email)}</small></td><td>${esc(l.company||'—')}<small>${esc(l.teamSize?l.teamSize+' kişi':'')}</small></td><td>${l.type==='upgrade'?'Plan talebi · ':''}${planName[l.plan]||'—'}</td><td>${statusPill(l.status)}</td><td>${l.nextAt?date(l.nextAt):'—'}</td><td>${dateTime(l.at)}</td></tr>`),'Henüz talep yok. Landing sayfasındaki demo formu dolduruldukça burada görünür.')}</section></div>`;},
 async site(){const d=await api('/api/admin/site');const groups=[...new Set(d.fields.map(f=>f.group))];
  return heading('Site içeriği',`Landing sayfasındaki metinler, rakamlar ve fiyatlar${d.updatedAt?` · son değişiklik ${dateTime(d.updatedAt)}`:''}`,`<a class="secondary" href="/" target="_blank" rel="noopener">${icon('external')} Siteyi aç</a>`)
  +`<p class="site-hint">Vurgu için kelimeyi yıldız içine alın: <code>*tek platformda*</code>. Yeni satır için Enter. Boş bırakılan alan varsayılan metni kullanır.</p><form id="siteForm" class="site-form">${groups.map(g=>`<section class="card"><div class="card-head"><h2>${esc(g)}</h2></div><div class="site-fields">${d.fields.filter(f=>f.group===g).map(f=>{const v=d.content[f.key]??'';return `<label class="field ${f.multiline||f.max>120?'wide':''}"><span>${esc(f.label)}${v!==''?' <i class="changed">değiştirildi</i>':''}</span>${f.multiline||f.key.endsWith('title')?`<textarea name="${f.key}" rows="${f.multiline?3:2}" maxlength="${f.max}" placeholder="${esc(f.default)}">${esc(v)}</textarea>`:`<input name="${f.key}" maxlength="${f.max}" value="${esc(v)}" placeholder="${esc(f.default||'Boş')}">`}</label>`;}).join('')}</div></section>`).join('')}<div class="site-actions"><button type="button" class="text-button" data-site-reset="1">Tümünü varsayılana döndür</button><button class="primary">Yayınla</button></div></form>`;},
 async overview(){const o=await load('overview','/api/admin/overview'),leads=await load('leads','/api/admin/leads'),max=Math.max(1,...o.days.map(d=>d.signups)),W=720,H=180,bw=W/o.days.length;
  const bars=o.days.map((d,i)=>{const h=d.signups/max*(H-40);return `<g class="wl-bar"><rect class="wl-hit" x="${i*bw}" y="0" width="${bw}" height="${H-20}"/>${h?`<path d="M${i*bw+3} ${H-20}V${H-20-h+3}Q${i*bw+3} ${H-20-h} ${i*bw+6} ${H-20-h}H${i*bw+bw-6}Q${i*bw+bw-3} ${H-20-h} ${i*bw+bw-3} ${H-20-h+3}V${H-20}Z"/>`:''}${i%5===0?`<text class="wl-axis" x="${i*bw+bw/2}" y="${H-4}" text-anchor="middle">${new Date(d.date).toLocaleDateString('tr-TR',{day:'numeric',month:'short'})}</text>`:''}<title>${date(d.date)}: ${d.signups} kayıt</title></g>`;}).join('');
  return heading('Platform',`Tüm çalışma alanları ve hesaplar · ${o.mailProvider==='resend'?'E-postalar Resend üzerinden gönderiliyor':'E-postalar kayda alınıyor, gönderilmiyor'}`,`<a class="secondary" href="/api/admin/accounts.csv">${icon('download')} Kullanıcıları dışa aktar</a>`)
  +`<section class="kpis">${kpi('Kullanıcı',o.accounts,`${o.newAccounts7} yeni · son 7 gün`)}${kpi('Aktif kullanıcı',o.active7,'Son 7 günde giriş')}${kpi('Pazarlama izni',o.consented,`%${o.accounts?Math.round(o.consented/o.accounts*100):0} izinli`)}${kpi('Çalışma alanı',o.spaces,`${o.trialActive} deneme · ${o.paid} ücretli`)}</section>`
  +`<div class="dash-grid"><section class="card span-8"><div class="card-head"><h2>Günlük kayıt</h2><span class="card-sub">Son 30 gün</span></div><svg class="workload" viewBox="0 0 ${W} ${H}" role="img" aria-label="Son 30 günün günlük kayıt sayısı">${bars}</svg></section><section class="card span-4"><div class="card-head"><h2>Planlar</h2></div>${o.plans.map(p=>`<div class="fin-bars"><div><span>${planName[p.plan]}</span><span class="bar"><i style="width:${o.spaces?p.count/o.spaces*100:0}%"></i></span><b>${p.count}</b></div></div>`).join('')}<p class="card-note">Süresi dolmuş deneme: <b>${o.trialExpired}</b></p></section><section class="card span-12"><div class="card-head"><h2>Son talepler</h2><button class="text-button" data-view="leads">Tümü</button></div>${table(['Tür','E-posta','Firma','Plan','Tarih'],leads.slice(0,6).map(l=>`<tr><td>${l.type==='upgrade'?'Plan talebi':'Demo talebi'}</td><td>${esc(l.email)}</td><td>${esc(l.company||'—')}</td><td>${planName[l.plan]||esc(l.plan)}</td><td>${dateTime(l.at)}</td></tr>`),'Henüz talep yok.')}</section></div>`;},
 async accounts(){const list=cache.accounts||await load('accounts','/api/admin/accounts');const q=query.toLocaleLowerCase('tr');
  const rows=list.filter(a=>(filter==='all'||filter==='consent'&&a.marketingConsent||filter==='noconsent'&&!a.marketingConsent||filter==='disabled'&&a.disabled||filter==='nospace'&&!a.spaces.length)&&`${a.name} ${a.email} ${a.phone} ${a.spaces.map(s=>s.name).join(' ')}`.toLocaleLowerCase('tr').includes(q));
  return heading('Kullanıcılar',`${list.length} hesap · ${list.filter(a=>a.marketingConsent).length} pazarlama izni`,`<a class="secondary" href="/api/admin/accounts.csv">${icon('download')} CSV</a>`)+`<div class="view-toolbar"><select id="accFilter">${[['all','Tüm hesaplar'],['consent','Pazarlama izni olanlar'],['noconsent','İzni olmayanlar'],['nospace','Çalışma alanı olmayanlar'],['disabled','Pasif hesaplar']].map(([k,n])=>`<option value="${k}" ${filter===k?'selected':''}>${n}</option>`).join('')}</select><label class="search-field">${icon('search')}<input id="adminSearch" value="${esc(query)}" placeholder="Ad, e-posta, telefon veya firma ara"></label></div>`
  +table(['Kişi','Telefon','Unvan / kaynak','İzin','Kayıt','Son giriş','Çalışma alanları',''],rows.map(a=>`<tr class="${a.disabled?'muted-row':''}"><td><b>${esc(a.name)}</b>${a.platformAdmin?' <span class="tag">Platform yöneticisi</span>':''}<small>${esc(a.email)}</small></td><td>${esc(a.phone||'—')}</td><td>${esc(a.title||'—')}<small>${esc(a.source||'')}</small></td><td>${a.marketingConsent?'<span class="state-text done">Var</span>':'<span class="state-text">Yok</span>'}</td><td>${date(a.createdAt)}</td><td>${dateTime(a.lastLoginAt)}</td><td>${a.spaces.map(s=>`${esc(s.name)}<small>${s.role==='admin'?'Yönetici':s.role==='lead'?'Proje sorumlusu':'Personel'}</small>`).join('')||'—'}</td><td class="row-actions">${a.id===me.id?'':`<button class="text-button" data-account="${a.id}" data-disabled="${!a.disabled}">${a.disabled?'Etkinleştir':'Pasifleştir'}</button>`}</td></tr>`),'Eşleşen hesap yok.');},
 async spaces(){const list=await load('spaces','/api/admin/spaces');
  return heading('Şirketler',`${list.length} çalışma alanı`)+table(['Firma','Sahip','Profil','Ekip','Proje','Plan','Kuruluş','İşlem'],list.map(s=>`<tr><td><b>${esc(s.name)}</b>${s.pendingInvites?`<small>${s.pendingInvites} bekleyen davet</small>`:''}</td><td>${s.owner?`${esc(s.owner.name)}<small>${esc(s.owner.email)}${s.owner.phone?' · '+esc(s.owner.phone):''}</small>`:'—'}</td><td>${esc(s.profile?.sector||'—')}<small>${[s.profile?.teamSize&&s.profile.teamSize+' kişi',s.profile?.city].filter(Boolean).map(esc).join(' · ')}</small></td><td>${s.members}</td><td>${s.projects}</td><td>${trialText(s)}${s.plan==='trial'?`<small>${date(s.trialEndsAt)}</small>`:''}</td><td>${date(s.createdAt)}</td><td class="row-actions"><select data-plan-space="${s.id}" aria-label="${esc(s.name)} planı">${Object.entries(planName).map(([k,n])=>`<option value="${k}" ${s.plan===k?'selected':''}>${n}</option>`).join('')}</select><button class="text-button" data-extend="${s.id}" data-days="7">+7 gün</button><button class="text-button" data-extend="${s.id}" data-days="14">+14 gün</button></td></tr>`),'Henüz çalışma alanı yok.');},
 async campaigns(){const a=await load('automations','/api/admin/automations');
  return heading('Kampanyalar','Pazarlama e-postaları yalnızca izin veren kişilere, abonelikten çıkma bağlantısıyla gönderilir.')+`<div class="dash-grid"><form id="campaignForm" class="card span-8 campaign-form"><div class="card-head"><h2>Yeni kampanya</h2></div><div class="form-grid"><label class="field"><span>Kampanya adı</span><input name="name" maxlength="120" placeholder="Örn. Ekim bülteni"></label><label class="field"><span>Hedef kitle</span><select name="segment">${a.segments.map(s=>`<option value="${s.id}">${esc(s.name)} (${s.count})</option>`).join('')}</select></label></div><label class="field"><span>Konu</span><input name="subject" required maxlength="160" placeholder="Örn. {{ad}}, finans modülü yenilendi"></label><label class="field"><span>İçerik</span><textarea name="body" rows="10" required placeholder="Merhaba {{ad}},&#10;&#10;..."></textarea></label><p class="field-hint">Değişkenler: {{ad}}, {{ad_soyad}}, {{eposta}}, {{firma}}, {{uygulama}}, {{deneme_bitis}}, {{kalan_gun}}</p><div class="form-actions"><button type="button" class="secondary" data-preview="campaign">${icon('eye')} Önizle</button><button class="primary">${icon('send')} Gönder</button></div></form><section class="card span-4"><div class="card-head"><h2>Geçmiş kampanyalar</h2></div>${a.campaigns.map(c=>`<div class="activity-row"><div><p><b>${esc(c.name)}</b></p><small>${esc(a.segments.find(s=>s.id===c.segment)?.name||c.segment)} · ${c.sent}/${c.recipients} gönderim · ${dateTime(c.createdAt)}</small></div></div>`).join('')||'<p class="card-empty">Henüz kampanya gönderilmedi.</p>'}</section></div>`;},
 async automations(){const a=await load('automations','/api/admin/automations');const trig={signup:'Hesap açıldığında',space_created:'Çalışma alanı kurulduğunda',invite:'Ekip daveti gönderildiğinde',trial_ending:'Denemenin bitmesine 3 gün kala',trial_expired:'Deneme süresi dolduğunda',inactive_14:'14 gün giriş yapılmadığında'};
  return heading('Otomasyonlar','Olay ve zaman tetiklemeli e-postalar. Zamanlı kurallar saatte bir çalışır.',`<button class="secondary" data-run="1">${icon('bolt')} Zamanlı kuralları şimdi çalıştır</button>`)+`<div class="auto-list">${a.rules.map(r=>`<form class="card auto-rule" data-rule="${r.id}"><div class="auto-head"><div><h2>${esc(r.name)}</h2><small>${trig[r.trigger]||r.trigger} · ${r.kind==='marketing'?'Pazarlama (izin gerekir)':'Hizmet bildirimi'} · ${a.stats[r.id]||0} gönderim</small></div>${r.locked?'<span class="tag">Her zaman açık</span>':`<label class="switch" title="Etkin"><input type="checkbox" name="enabled" ${r.enabled?'checked':''}><span></span></label>`}</div><details><summary>İçeriği düzenle</summary><label class="field"><span>Konu</span><input name="subject" value="${esc(r.subject)}" maxlength="160"></label><label class="field"><span>İçerik</span><textarea name="body" rows="8">${esc(r.body)}</textarea></label><div class="form-actions"><button type="button" class="secondary" data-preview="${r.id}">${icon('eye')} Önizle</button><button class="primary">Kaydet</button></div></details></form>`).join('')}</div>`;},
 async outbox(){const list=await load('outbox','/api/admin/outbox');
  return heading('E-posta kutusu',`Son ${list.length} e-posta`)+table(['Tarih','Alıcı','Konu','Tür','Durum'],list.map((e,i)=>`<tr class="clickable" data-mail="${i}"><td>${dateTime(e.createdAt)}</td><td>${esc(e.to)}</td><td><b>${esc(e.subject)}</b></td><td>${e.kind==='marketing'?'Pazarlama':'Hizmet'}<small>${esc(e.tag)}</small></td><td>${e.status==='sent'?'<span class="state-text done">Gönderildi</span>':e.status==='failed'?`<span class="state-text late" title="${esc(e.error||'')}">Başarısız</span>`:'<span class="state-text">Kayıtta</span>'}</td></tr>`),'Henüz e-posta yok.');},
 async leads(){const list=cache.leads=await api('/api/admin/leads');const q=leadQuery.toLocaleLowerCase('tr');const count=k=>list.filter(l=>(l.status||'new')===k).length;
  const rows=list.filter(l=>(leadFilter==='all'||(l.status||'new')===leadFilter)&&`${l.name} ${l.email} ${l.company} ${l.phone}`.toLocaleLowerCase('tr').includes(q));
  return heading('Talepler',`${list.length} talep · demo formu ve uygulama içi plan talepleri`,`<a class="secondary" href="/api/admin/leads.csv">${icon('download')} CSV</a>`)
  +`<div class="view-toolbar"><div class="segmented wrap" role="group" aria-label="Durum">${[['all','Tümü',list.length],...Object.entries(LEAD_STATUS).map(([k,n])=>[k,n,count(k)])].map(([k,n,c])=>`<button class="${leadFilter===k?'on':''}" data-lead-filter="${k}">${n} <span>${c}</span></button>`).join('')}</div><label class="search-field">${icon('search')}<input id="leadSearch" value="${esc(leadQuery)}" placeholder="Ad, e-posta, firma veya telefon ara"></label></div>`
  +table(['Kişi','Firma','Ekip / plan','Durum','Takip','Geliş',''],rows.map(l=>`<tr class="clickable" data-lead-open="${l.id}"><td><b>${esc(l.name||'—')}</b><small>${esc(l.email)}${l.phone?' · '+esc(l.phone):''}</small></td><td>${esc(l.company||'—')}</td><td>${esc(l.teamSize?l.teamSize+' kişi':'—')}<small>${l.type==='upgrade'?'Plan talebi · ':''}${planName[l.plan]||esc(l.plan||'')}</small></td><td><select class="lead-status-select" data-lead-status="${l.id}" aria-label="Durum">${Object.entries(LEAD_STATUS).map(([k,n])=>`<option value="${k}" ${(l.status||'new')===k?'selected':''}>${n}</option>`).join('')}</select></td><td class="${l.nextAt&&l.nextAt<=new Date().toISOString().slice(0,10)&&!['won','lost'].includes(l.status||'new')?'due-cell':''}">${l.nextAt?date(l.nextAt):'—'}</td><td>${dateTime(l.at)}${l.notes?.length?`<small>${l.notes.length} not</small>`:''}</td><td class="row-actions"><button class="text-button" data-lead-open="${l.id}">Aç</button></td></tr>`),'Bu filtrede talep yok.');}
};
async function preview(subject,body,kind){const html=await api('/api/admin/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body,kind})});modal(subject||'Önizleme',`<iframe class="mail-preview" title="E-posta önizlemesi" sandbox="" srcdoc="${esc(html)}"></iframe>`,true);}
document.addEventListener('click',async e=>{if(e.target.closest('select,a,input'))return;const row=e.target.closest('[data-lead-open]');if(row){const l=(cache.leads||[]).find(x=>x.id===row.dataset.leadOpen);if(l)modal(l.name||l.email,leadDetail(l),true);return;}const b=e.target.closest('button,[data-mail]');if(!b)return;
 if(b.hasAttribute('data-close')){b.closest('dialog').close();return;}
 if(b.dataset.view){view=b.dataset.view;history.replaceState(null,'','#'+view);query='';filter='all';delete cache.accounts;return render();}
 if(b.dataset.range){range=Number(b.dataset.range);return render();}
 if(b.dataset.leadFilter){leadFilter=b.dataset.leadFilter;if(view!=='leads'){view='leads';history.replaceState(null,'','#leads');}return render();}
 try{
  if(b.dataset.leadDelete){if(!confirm('Talep kalıcı olarak silinsin mi? (KVKK silme talepleri için)'))return;await post('/api/admin/leads/'+b.dataset.leadDelete,{delete:true});$('#modal').close();toast('Talep silindi.');return render();}
  if(b.dataset.siteReset){if(!confirm('Tüm site metinleri varsayılana dönsün mü?'))return;await post('/api/admin/site',{content:{}});toast('Varsayılan metinler yayında.');return render();}
  if(b.dataset.account){await post('/api/admin/accounts/'+b.dataset.account,{disabled:b.dataset.disabled==='true'});delete cache.accounts;toast('Hesap güncellendi.');return render();}
  if(b.dataset.extend){await post('/api/admin/spaces/'+b.dataset.extend,{extendDays:Number(b.dataset.days)});toast(`Deneme ${b.dataset.days} gün uzatıldı.`);return render();}
  if(b.dataset.run){const r=await post('/api/admin/automations/run');toast(`${r.sent} e-posta gönderildi.`);return render();}
  if(b.dataset.preview){const f=b.closest('form');return preview(f.subject.value,f.body.value,b.dataset.preview==='campaign'||cache.automations?.rules.find(r=>r.id===b.dataset.preview)?.kind==='marketing'?'marketing':'service');}
  if(b.dataset.mail!==undefined){const m=cache.outbox[Number(b.dataset.mail)];return modal(m.subject,`<p class="body-copy"><b>Alıcı:</b> ${esc(m.to)} · ${dateTime(m.createdAt)}</p><pre class="mail-text">${esc(m.text)}</pre>`,true);}
 }catch(err){toast(err.message,true);}
});
document.addEventListener('change',async e=>{const t=e.target;try{
 if(t.dataset.planSpace){await post('/api/admin/spaces/'+t.dataset.planSpace,{plan:t.value});toast('Plan güncellendi.');return render();}
 if(t.dataset.leadStatus){await post('/api/admin/leads/'+t.dataset.leadStatus,{status:t.value});toast('Durum güncellendi.');cache.leads=await api('/api/admin/leads');return;}
 if(t.id==='accFilter'){filter=t.value;$('#main').innerHTML=await renderers.accounts();}
 if(t.name==='enabled'&&t.closest('.auto-rule')){await post('/api/admin/automations/'+t.closest('.auto-rule').dataset.rule,{enabled:t.checked});toast(t.checked?'Otomasyon açıldı.':'Otomasyon kapatıldı.');}
}catch(err){toast(err.message,true);}});
document.addEventListener('input',async e=>{if(e.target.id==='leadSearch'){leadQuery=e.target.value;const pos=e.target.selectionStart;$('#main').innerHTML=await renderers.leads();const i=$('#leadSearch');i.focus();i.setSelectionRange(pos,pos);return;}if(e.target.id==='adminSearch'){query=e.target.value;const pos=e.target.selectionStart;$('#main').innerHTML=await renderers.accounts();const i=$('#adminSearch');i.focus();i.setSelectionRange(pos,pos);}});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f));try{
 if(f.id==='leadForm'){const l=await post('/api/admin/leads/'+f.dataset.id,{status:v.status,nextAt:v.nextAt,value:v.value===''?undefined:Number(v.value),note:v.note});cache.leads=await api('/api/admin/leads');modal(l.name||l.email,leadDetail(l),true);toast('Talep güncellendi.');if(view!=='site')$('#main').innerHTML=await renderers[view]();return;}
 if(f.id==='siteForm'){await post('/api/admin/site',{content:v});toast('Site içeriği yayınlandı. Değişiklik bir dakika içinde görünür.');return render();}
 if(f.id==='campaignForm'){const seg=f.segment.selectedOptions[0].textContent;if(!confirm(`"${v.subject}" konulu e-posta şu kitleye gönderilecek: ${seg}. Onaylıyor musunuz?`))return;const c=await post('/api/admin/campaigns',v);toast(`${c.sent} kişiye gönderildi.`);return render();}
 if(f.classList.contains('auto-rule')){await post('/api/admin/automations/'+f.dataset.rule,{subject:v.subject,body:v.body});toast('Otomasyon içeriği kaydedildi.');}
}catch(err){toast(err.message,true);}});
(async()=>{try{const s=await api('/api/session');if(!s.user){location.href='/app';return;}me=s.user;if(!me.platformAdmin){$('#main').innerHTML='<div class="empty"><h3>Bu alan platform yöneticileri içindir</h3><p>Hesabınızın bu sayfaya erişimi yok.</p><a class="primary" href="/app">Uygulamaya dön</a></div>';return;}if(!views[view])view='sales';render();}catch(e){$('#main').innerHTML=`<div class="empty"><h3>Bağlanılamadı</h3><p>${esc(e.message)}</p></div>`;}})();
