// Platform administration: accounts, companies, plans, campaigns, automations, outbox and leads.
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const P={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m18 0v-2a4 4 0 0 0-3-3.87M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8m8 0a4 4 0 0 1 0 8',building:'M3 21V7l9-4 9 4v14M8 21v-6h8v6M8 9v2m8-2v2M1 21h22',send:'M22 2 11 13 M22 2l-7 20-4-9-9-4z',bolt:'M13 2 3 14h9l-1 8 10-12h-9z',mail:'M3 5h18v14H3z M3 6l9 7 9-7',inbox:'M22 12h-6l-2 3h-4l-2-3H2 M5 5h14l3 7v7H2v-7z',back:'M19 12H5 M11 6l-6 6 6 6',download:'M12 3v12 M7 10l5 5 5-5 M4 21h16',close:'M18 6 6 18M6 6l12 12',check:'m5 12 4 4L19 6',search:'M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14z M21 21l-4.3-4.3',eye:'M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12z M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z'};
const icon=n=>`<svg class="icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${P[n]}"/></svg>`;
const api=async(url,opt={})=>{const r=await fetch(url,opt);const t=r.headers.get('content-type')||'';const body=t.includes('json')?await r.json():await r.text();if(!r.ok)throw Error(body.error||'İstek başarısız.');return body;};
const post=(url,b)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b||{})});
const date=d=>d?new Date(d).toLocaleDateString('tr-TR',{day:'numeric',month:'short',year:'numeric'}):'—';
const dateTime=d=>d?new Date(d).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const planName={trial:'Deneme',ekip:'Ekip',buro:'Büro',kurumsal:'Kurumsal'};
const toast=(text,error=false)=>{const el=document.createElement('div');el.className='toast'+(error?' error':'');el.innerHTML=icon(error?'close':'check')+`<span>${esc(text)}</span>`;$('#toasts').append(el);setTimeout(()=>el.remove(),4500);};
const modal=(title,html,wide)=>{const m=$('#modal');m.className=wide?'wide':'';m.innerHTML=`<div class="modal-head"><div><h2>${esc(title)}</h2></div><button class="icon-button" data-close aria-label="Kapat">${icon('close')}</button></div>${html}`;if(!m.open)m.showModal();};
const heading=(title,sub,actions='')=>`<div class="page-heading"><div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="heading-actions">${actions}</div></div>`;
const views={overview:['Genel bakış','grid'],accounts:['Kullanıcılar','users'],spaces:['Şirketler','building'],campaigns:['Kampanyalar','send'],automations:['Otomasyonlar','bolt'],outbox:['E-posta kutusu','inbox'],leads:['Talepler','mail']};
let view=location.hash.slice(1)||'overview',me=null,cache={},query='',filter='all';
try{const t=localStorage.getItem('buros-theme');document.documentElement.dataset.theme=t==='gece'?'gece':'orman';}catch{}

function chrome(){
 $('#sidebar').innerHTML=`<div class="sb-top"><a class="brand" href="/app" aria-label="Uygulamaya dön"><img src="/brand/logo.svg" alt="bürOS" height="28"></a></div><div class="admin-tag">Platform yönetimi</div><nav>${Object.entries(views).map(([k,[n,ic]])=>`<button class="nav-item ${view===k?'active':''}" data-view="${k}">${icon(ic)}<span>${n}</span></button>`).join('')}</nav><div class="sidebar-end"><a class="nav-item" href="/app">${icon('back')}<span>Uygulamaya dön</span></a><div class="profile"><span class="avatar">${esc((me.name||'').split(' ').map(x=>x[0]).slice(0,2).join(''))}</span><span class="profile-text"><b>${esc(me.name)}</b><small>${esc(me.email)}</small></span></div></div>`;
 $('#header').innerHTML=`<div class="breadcrumb"><b>${views[view][0]}</b></div><div></div><div class="header-tools"><span class="sync" data-state="saved"><span class="sync-icon"></span><span>Canlı veri</span></span></div>`;
}
async function load(key,url){cache[key]=await api(url);return cache[key];}
async function render(){chrome();const main=$('#main');main.innerHTML='<div class="loading"><small>Yükleniyor…</small></div>';try{main.innerHTML=await renderers[view]();}catch(e){main.innerHTML=`<div class="empty"><h3>Veri alınamadı</h3><p>${esc(e.message)}</p></div>`;}}
const kpi=(label,value,sub='',cls='')=>`<div class="kpi ${cls}"><span class="kpi-label">${label}</span><strong>${value}</strong><small>${sub}</small></div>`;
const table=(head,rows,empty='Kayıt yok.')=>`<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}"><p class="card-empty">${empty}</p></td></tr>`}</tbody></table></div>`;
const trialText=s=>s.plan!=='trial'?`<span class="state-text done">${planName[s.plan]}</span>`:s.expired?'<span class="state-text late">Deneme bitti</span>':`<span class="state-text">Deneme · ${s.daysLeft} gün</span>`;

const renderers={
 async overview(){const o=await load('overview','/api/admin/overview'),leads=await load('leads','/api/admin/leads'),max=Math.max(1,...o.days.map(d=>d.signups)),W=720,H=180,bw=W/o.days.length;
  const bars=o.days.map((d,i)=>{const h=d.signups/max*(H-40);return `<g class="wl-bar"><rect class="wl-hit" x="${i*bw}" y="0" width="${bw}" height="${H-20}"/>${h?`<path d="M${i*bw+3} ${H-20}V${H-20-h+3}Q${i*bw+3} ${H-20-h} ${i*bw+6} ${H-20-h}H${i*bw+bw-6}Q${i*bw+bw-3} ${H-20-h} ${i*bw+bw-3} ${H-20-h+3}V${H-20}Z"/>`:''}${i%5===0?`<text class="wl-axis" x="${i*bw+bw/2}" y="${H-4}" text-anchor="middle">${new Date(d.date).toLocaleDateString('tr-TR',{day:'numeric',month:'short'})}</text>`:''}<title>${date(d.date)}: ${d.signups} kayıt</title></g>`;}).join('');
  return heading('Platform',`Tüm çalışma alanları ve hesaplar · ${o.mailProvider==='resend'?'E-postalar Resend üzerinden gönderiliyor':'E-postalar kayda alınıyor, gönderilmiyor'}`,`<a class="secondary" href="/api/admin/accounts.csv">${icon('download')} Kullanıcıları dışa aktar</a>`)
  +`<section class="kpis">${kpi('Kullanıcı',o.accounts,`${o.newAccounts7} yeni · son 7 gün`)}${kpi('Aktif kullanıcı',o.active7,'Son 7 günde giriş')}${kpi('Pazarlama izni',o.consented,`%${o.accounts?Math.round(o.consented/o.accounts*100):0} izinli`)}${kpi('Çalışma alanı',o.spaces,`${o.trialActive} deneme · ${o.paid} ücretli`)}</section>`
  +`<div class="dash-grid"><section class="card span-8"><div class="card-head"><h2>Günlük kayıt</h2><span class="card-sub">Son 30 gün</span></div><svg class="workload" viewBox="0 0 ${W} ${H}" role="img" aria-label="Son 30 günün günlük kayıt sayısı">${bars}</svg></section><section class="card span-4"><div class="card-head"><h2>Planlar</h2></div>${o.plans.map(p=>`<div class="fin-bars"><div><span>${planName[p.plan]}</span><span class="bar"><i style="width:${o.spaces?p.count/o.spaces*100:0}%"></i></span><b>${p.count}</b></div></div>`).join('')}<p class="card-note">Süresi dolmuş deneme: <b>${o.trialExpired}</b></p></section><section class="card span-12"><div class="card-head"><h2>Son talepler</h2><button class="text-button" data-view="leads">Tümü</button></div>${table(['Tür','E-posta','Firma','Plan','Tarih'],leads.slice(0,6).map(l=>`<tr><td>${l.type==='upgrade'?'Plan talebi':'Demo talebi'}</td><td>${esc(l.email)}</td><td>${esc(l.company||'—')}</td><td>${planName[l.plan]||esc(l.plan)}</td><td>${dateTime(l.at)}</td></tr>`),'Henüz talep yok.')}</section></div>`;},
 async accounts(){const list=cache.accounts||await load('accounts','/api/admin/accounts');const q=query.toLocaleLowerCase('tr');
  const rows=list.filter(a=>(filter==='all'||filter==='consent'&&a.marketingConsent||filter==='noconsent'&&!a.marketingConsent||filter==='disabled'&&a.disabled||filter==='nospace'&&!a.spaces.length)&&`${a.name} ${a.email} ${a.phone} ${a.spaces.map(s=>s.name).join(' ')}`.toLocaleLowerCase('tr').includes(q));
  return heading('Kullanıcılar',`${list.length} hesap · ${list.filter(a=>a.marketingConsent).length} pazarlama izni`,`<a class="secondary" href="/api/admin/accounts.csv">${icon('download')} CSV</a>`)+`<div class="view-toolbar"><select id="accFilter">${[['all','Tüm hesaplar'],['consent','Pazarlama izni olanlar'],['noconsent','İzni olmayanlar'],['nospace','Çalışma alanı olmayanlar'],['disabled','Pasif hesaplar']].map(([k,n])=>`<option value="${k}" ${filter===k?'selected':''}>${n}</option>`).join('')}</select><label class="search-field">${icon('search')}<input id="adminSearch" value="${esc(query)}" placeholder="Ad, e-posta, telefon veya firma ara"></label></div>`
  +table(['Kişi','Telefon','Unvan / kaynak','İzin','Kayıt','Son giriş','Çalışma alanları',''],rows.map(a=>`<tr class="${a.disabled?'muted-row':''}"><td><b>${esc(a.name)}</b>${a.platformAdmin?' <span class="tag">Platform yöneticisi</span>':''}<small>${esc(a.email)}</small></td><td>${esc(a.phone||'—')}</td><td>${esc(a.title||'—')}<small>${esc(a.source||'')}</small></td><td>${a.marketingConsent?'<span class="state-text done">Var</span>':'<span class="state-text">Yok</span>'}</td><td>${date(a.createdAt)}</td><td>${dateTime(a.lastLoginAt)}</td><td>${a.spaces.map(s=>`${esc(s.name)}<small>${s.role==='admin'?'Yönetici':s.role==='lead'?'Proje sorumlusu':'Personel'}</small>`).join('')||'—'}</td><td class="row-actions">${a.id===me.id?'':`<button class="text-button" data-account="${a.id}" data-disabled="${!a.disabled}">${a.disabled?'Etkinleştir':'Pasifleştir'}</button>`}</td></tr>`),'Eşleşen hesap yok.');},
 async spaces(){const list=await load('spaces','/api/admin/spaces');
  return heading('Şirketler',`${list.length} çalışma alanı`)+table(['Firma','Sahip','Profil','Ekip','Proje','Plan','Kuruluş','İşlem'],list.map(s=>`<tr><td><b>${esc(s.name)}</b>${s.pendingInvites?`<small>${s.pendingInvites} bekleyen davet</small>`:''}</td><td>${s.owner?`${esc(s.owner.name)}<small>${esc(s.owner.email)}${s.owner.phone?' · '+esc(s.owner.phone):''}</small>`:'—'}</td><td>${esc(s.profile?.sector||'—')}<small>${[s.profile?.teamSize&&s.profile.teamSize+' kişi',s.profile?.city].filter(Boolean).map(esc).join(' · ')}</small></td><td>${s.members}</td><td>${s.projects}</td><td>${trialText(s)}${s.plan==='trial'?`<small>${date(s.trialEndsAt)}</small>`:''}</td><td>${date(s.createdAt)}</td><td class="row-actions"><select data-plan-space="${s.id}" aria-label="${esc(s.name)} planı">${Object.entries(planName).map(([k,n])=>`<option value="${k}" ${s.plan===k?'selected':''}>${n}</option>`).join('')}</select><button class="text-button" data-extend="${s.id}" data-days="7">+7 gün</button><button class="text-button" data-extend="${s.id}" data-days="14">+14 gün</button></td></tr>`),'Henüz çalışma alanı yok.');},
 async campaigns(){const a=await load('automations','/api/admin/automations');
  return heading('Kampanyalar','Pazarlama e-postaları yalnızca izin veren kişilere, abonelikten çıkma bağlantısıyla gönderilir.')+`<div class="dash-grid"><form id="campaignForm" class="card span-8 campaign-form"><div class="card-head"><h2>Yeni kampanya</h2></div><div class="form-grid"><label class="field"><span>Kampanya adı</span><input name="name" maxlength="120" placeholder="Örn. Ekim bülteni"></label><label class="field"><span>Hedef kitle</span><select name="segment">${a.segments.map(s=>`<option value="${s.id}">${esc(s.name)} (${s.count})</option>`).join('')}</select></label></div><label class="field"><span>Konu</span><input name="subject" required maxlength="160" placeholder="Örn. {{ad}}, finans modülü yenilendi"></label><label class="field"><span>İçerik</span><textarea name="body" rows="10" required placeholder="Merhaba {{ad}},&#10;&#10;..."></textarea></label><p class="field-hint">Değişkenler: {{ad}}, {{ad_soyad}}, {{eposta}}, {{firma}}, {{uygulama}}, {{deneme_bitis}}, {{kalan_gun}}</p><div class="form-actions"><button type="button" class="secondary" data-preview="campaign">${icon('eye')} Önizle</button><button class="primary">${icon('send')} Gönder</button></div></form><section class="card span-4"><div class="card-head"><h2>Geçmiş kampanyalar</h2></div>${a.campaigns.map(c=>`<div class="activity-row"><div><p><b>${esc(c.name)}</b></p><small>${esc(a.segments.find(s=>s.id===c.segment)?.name||c.segment)} · ${c.sent}/${c.recipients} gönderim · ${dateTime(c.createdAt)}</small></div></div>`).join('')||'<p class="card-empty">Henüz kampanya gönderilmedi.</p>'}</section></div>`;},
 async automations(){const a=await load('automations','/api/admin/automations');const trig={signup:'Hesap açıldığında',space_created:'Çalışma alanı kurulduğunda',invite:'Ekip daveti gönderildiğinde',trial_ending:'Denemenin bitmesine 3 gün kala',trial_expired:'Deneme süresi dolduğunda',inactive_14:'14 gün giriş yapılmadığında'};
  return heading('Otomasyonlar','Olay ve zaman tetiklemeli e-postalar. Zamanlı kurallar saatte bir çalışır.',`<button class="secondary" data-run="1">${icon('bolt')} Zamanlı kuralları şimdi çalıştır</button>`)+`<div class="auto-list">${a.rules.map(r=>`<form class="card auto-rule" data-rule="${r.id}"><div class="auto-head"><div><h2>${esc(r.name)}</h2><small>${trig[r.trigger]||r.trigger} · ${r.kind==='marketing'?'Pazarlama (izin gerekir)':'Hizmet bildirimi'} · ${a.stats[r.id]||0} gönderim</small></div>${r.locked?'<span class="tag">Her zaman açık</span>':`<label class="switch" title="Etkin"><input type="checkbox" name="enabled" ${r.enabled?'checked':''}><span></span></label>`}</div><details><summary>İçeriği düzenle</summary><label class="field"><span>Konu</span><input name="subject" value="${esc(r.subject)}" maxlength="160"></label><label class="field"><span>İçerik</span><textarea name="body" rows="8">${esc(r.body)}</textarea></label><div class="form-actions"><button type="button" class="secondary" data-preview="${r.id}">${icon('eye')} Önizle</button><button class="primary">Kaydet</button></div></details></form>`).join('')}</div>`;},
 async outbox(){const list=await load('outbox','/api/admin/outbox');
  return heading('E-posta kutusu',`Son ${list.length} e-posta`)+table(['Tarih','Alıcı','Konu','Tür','Durum'],list.map((e,i)=>`<tr class="clickable" data-mail="${i}"><td>${dateTime(e.createdAt)}</td><td>${esc(e.to)}</td><td><b>${esc(e.subject)}</b></td><td>${e.kind==='marketing'?'Pazarlama':'Hizmet'}<small>${esc(e.tag)}</small></td><td>${e.status==='sent'?'<span class="state-text done">Gönderildi</span>':e.status==='failed'?`<span class="state-text late" title="${esc(e.error||'')}">Başarısız</span>`:'<span class="state-text">Kayıtta</span>'}</td></tr>`),'Henüz e-posta yok.');},
 async leads(){const list=await load('leads','/api/admin/leads');
  return heading('Talepler','Landing sayfasındaki demo talepleri ve uygulama içinden gelen plan talepleri')+table(['Tür','E-posta','Ad','Firma','Plan','Tarih'],list.map(l=>`<tr><td>${l.type==='upgrade'?'Plan talebi':'Demo talebi'}</td><td><a href="mailto:${esc(l.email)}">${esc(l.email)}</a></td><td>${esc(l.name||'—')}</td><td>${esc(l.company||'—')}</td><td>${planName[l.plan]||esc(l.plan)}</td><td>${dateTime(l.at)}</td></tr>`),'Henüz talep yok.');}
};
async function preview(subject,body,kind){const html=await api('/api/admin/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body,kind})});modal(subject||'Önizleme',`<iframe class="mail-preview" title="E-posta önizlemesi" sandbox="" srcdoc="${esc(html)}"></iframe>`,true);}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-mail]');if(!b)return;
 if(b.hasAttribute('data-close')){b.closest('dialog').close();return;}
 if(b.dataset.view){view=b.dataset.view;history.replaceState(null,'','#'+view);query='';filter='all';delete cache.accounts;return render();}
 try{
  if(b.dataset.account){await post('/api/admin/accounts/'+b.dataset.account,{disabled:b.dataset.disabled==='true'});delete cache.accounts;toast('Hesap güncellendi.');return render();}
  if(b.dataset.extend){await post('/api/admin/spaces/'+b.dataset.extend,{extendDays:Number(b.dataset.days)});toast(`Deneme ${b.dataset.days} gün uzatıldı.`);return render();}
  if(b.dataset.run){const r=await post('/api/admin/automations/run');toast(`${r.sent} e-posta gönderildi.`);return render();}
  if(b.dataset.preview){const f=b.closest('form');return preview(f.subject.value,f.body.value,b.dataset.preview==='campaign'||cache.automations?.rules.find(r=>r.id===b.dataset.preview)?.kind==='marketing'?'marketing':'service');}
  if(b.dataset.mail!==undefined){const m=cache.outbox[Number(b.dataset.mail)];return modal(m.subject,`<p class="body-copy"><b>Alıcı:</b> ${esc(m.to)} · ${dateTime(m.createdAt)}</p><pre class="mail-text">${esc(m.text)}</pre>`,true);}
 }catch(err){toast(err.message,true);}
});
document.addEventListener('change',async e=>{const t=e.target;try{
 if(t.dataset.planSpace){await post('/api/admin/spaces/'+t.dataset.planSpace,{plan:t.value});toast('Plan güncellendi.');return render();}
 if(t.id==='accFilter'){filter=t.value;$('#main').innerHTML=await renderers.accounts();}
 if(t.name==='enabled'&&t.closest('.auto-rule')){await post('/api/admin/automations/'+t.closest('.auto-rule').dataset.rule,{enabled:t.checked});toast(t.checked?'Otomasyon açıldı.':'Otomasyon kapatıldı.');}
}catch(err){toast(err.message,true);}});
document.addEventListener('input',async e=>{if(e.target.id==='adminSearch'){query=e.target.value;const pos=e.target.selectionStart;$('#main').innerHTML=await renderers.accounts();const i=$('#adminSearch');i.focus();i.setSelectionRange(pos,pos);}});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f));try{
 if(f.id==='campaignForm'){const seg=f.segment.selectedOptions[0].textContent;if(!confirm(`"${v.subject}" konulu e-posta şu kitleye gönderilecek: ${seg}. Onaylıyor musunuz?`))return;const c=await post('/api/admin/campaigns',v);toast(`${c.sent} kişiye gönderildi.`);return render();}
 if(f.classList.contains('auto-rule')){await post('/api/admin/automations/'+f.dataset.rule,{subject:v.subject,body:v.body});toast('Otomasyon içeriği kaydedildi.');}
}catch(err){toast(err.message,true);}});
(async()=>{try{const s=await api('/api/session');if(!s.user){location.href='/app';return;}me=s.user;if(!me.platformAdmin){$('#main').innerHTML='<div class="empty"><h3>Bu alan platform yöneticileri içindir</h3><p>Hesabınızın bu sayfaya erişimi yok.</p><a class="primary" href="/app">Uygulamaya dön</a></div>';return;}if(!views[view])view='overview';render();}catch(e){$('#main').innerHTML=`<div class="empty"><h3>Bağlanılamadı</h3><p>${esc(e.message)}</p></div>`;}})();
