export const uid=()=>crypto.randomUUID();
export const dateKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export const offsetDate=n=>{const d=new Date();d.setDate(d.getDate()+n);return dateKey(d);};
export const allItems=data=>data.projects.flatMap(p=>p.sections.flatMap(s=>s.items.map(o=>({...o,project:p,section:s}))));
export const stateOf=(data,o)=>data.workflows.find(w=>w.id===o.workflowId)?.states.find(s=>s.id===o.stateId);
export const completed=(data,o)=>stateOf(data,o)?.type==='completed';
export const overdue=(data,o)=>!!o.date&&o.date<dateKey()&&!completed(data,o);
export const progress=(data,p)=>{const groups=p.sections.filter(s=>s.items.length);const total=groups.reduce((n,s)=>n+(Number(s.weight)||1),0);return total?Math.round(groups.reduce((n,s)=>n+s.items.reduce((a,o)=>a+(stateOf(data,o)?.progress||0),0)/s.items.length*(Number(s.weight)||1),0)/total):0;};
export function newItem(data,name,workflowId='documents'){const w=data.workflows.find(w=>w.id===workflowId)||data.workflows[0];return{id:uid(),name,workflowId:w.id,stateId:w.states[0].id,owner:'',date:'',notes:'',properties:[],files:[],comments:[]};}
export function fromTemplate(data,{name,clientId,location,templateId}){const t=data.templates.find(t=>t.id===templateId);return{id:uid(),name,clientId,location,createdAt:new Date().toISOString(),archived:false,cover:data.projects.length%4,sections:t?t.sections.map(s=>({id:uid(),name:s.name,weight:s.weight||1,items:s.items.map(o=>({...newItem(data,o.name,o.workflowId),properties:(o.properties||[]).map(p=>({...p,id:uid(),value:p.type==='checkbox'?false:''}))}))})):[]};}
export const FINANCE_FLOW=()=>({id:'finans',name:'Finans',scope:'finance',states:[{id:'planned',name:'Planlandı',progress:0,type:'pending',color:'gray'},{id:'invoiced',name:'Faturalandı',progress:50,type:'active',color:'blue'},{id:'paid',name:'Ödendi',progress:100,type:'completed',color:'green'}]});
export const itemWorkflows=d=>d.workflows.filter(w=>w.scope!=='finance');
export const financeFlow=d=>d.workflows.find(w=>w.scope==='finance')||FINANCE_FLOW();
export function seed(){
const data={version:2,revision:0,settings:{name:'Başak Mimarlık',person:'Ayşe Yılmaz',role:'Mimar',compact:false,defaultBanners:true},clients:[{id:'denizli',name:'Denizli İnşaat',contact:'Ahmet Denizli',email:'',phone:'',notes:''},{id:'asfa',name:'Asfa Yapı',contact:'Selin Kaya',email:'',phone:'',notes:''},{id:'ege',name:'Ege Yaşam',contact:'Eren Yıldız',email:'',phone:'',notes:''}],workflows:[{id:'documents',name:'Evrak süreci',states:[{id:'waiting',name:'Bekleniyor',progress:0,type:'pending',color:'gray'},{id:'preparing',name:'Hazırlanıyor',progress:25,type:'active',color:'blue'},{id:'applied',name:'Başvuruda',progress:60,type:'active',color:'purple'},{id:'delivered',name:'Teslim edildi',progress:100,type:'completed',color:'green'}]},{id:'design',name:'Projelendirme',states:[{id:'todo',name:'Başlanmadı',progress:0,type:'pending',color:'gray'},{id:'doing',name:'Devam ediyor',progress:40,type:'active',color:'blue'},{id:'review',name:'Kontrolde',progress:75,type:'active',color:'orange'},{id:'done',name:'Tamamlandı',progress:100,type:'completed',color:'green'}]},FINANCE_FLOW()],templates:[],projects:[],activity:[],finance:[]};
data.templates=[{id:'permit',name:'Standart Yapı Ruhsatı',description:'İlk evraktan ruhsata, bütün süreç bir arada.',sections:[{name:'Evraklar',weight:3,items:['Tapu','Aplikasyon Krokisi','İmar Durumu','Kot Kesit','Zemin Etüdü'].map(name=>({name,workflowId:'documents'}))},{name:'Projelendirme',weight:4,items:['Mimari Proje','Statik Proje','Elektrik Projesi','Mekanik Proje'].map(name=>({name,workflowId:'design'}))},{name:'Resmî Süreçler',weight:3,items:['Belediye Başvurusu','Proje Kontrolü','Yapı Ruhsatı'].map(name=>({name,workflowId:'documents'}))}]},{id:'interior',name:'İç Mimari',description:'Konsept, uygulama ve teslim için sade bir başlangıç.',sections:[{name:'Tasarım',weight:1,items:['İhtiyaç Programı','Konsept Tasarım','Uygulama Projesi'].map(name=>({name,workflowId:'design'}))},{name:'Uygulama',weight:1,items:['Malzeme Seçimi','Saha Kontrolü','Teslim'].map(name=>({name,workflowId:'documents'}))}]}];
[['A Şantiyesi','denizli','Bakırköy, İstanbul'],['Vadi Evleri','asfa','Beykoz, İstanbul'],['B Şantiyesi','denizli','Kadıköy, İstanbul'],['Urla Villa','ege','Urla, İzmir']].forEach(([name,clientId,location],pi)=>{const p=fromTemplate(data,{name,clientId,location,templateId:'permit'});p.sections.forEach((s,si)=>s.items.forEach((o,i)=>{const w=data.workflows.find(w=>w.id===o.workflowId);o.stateId=w.states[Math.max(0,Math.min(3,3-si-(i%2)-(pi%3)))].id;o.owner=['Ayşe Yılmaz','Ahmet Kaya','Murat Demir'][i%3];o.date=offsetDate(i+si*2-pi);if(o.name==='İmar Durumu'){o.notes='Belediye başvurusu için evraklar kontrol edilecek.';o.properties=[{id:uid(),name:'Belediye',type:'text',value:'Bakırköy Belediyesi'},{id:uid(),name:'Başvuru no',type:'text',value:'2026/18372'}];}}));data.projects.push(p);});
data.projects.slice(0,2).forEach((p,i)=>{const now=new Date().toISOString();data.finance.push({id:uid(),projectId:p.id,title:'1. Hakediş',type:'income',status:'paid',amount:180000+i*40000,date:offsetDate(-34-i*5),category:'Hakediş',notes:'',createdAt:now,createdBy:data.settings.person},{id:uid(),projectId:p.id,title:'2. Hakediş',type:'income',status:'invoiced',amount:150000+i*20000,date:offsetDate(-6),category:'Hakediş',notes:'',createdAt:now,createdBy:data.settings.person},{id:uid(),projectId:p.id,title:'Statik proje taşeron ödemesi',type:'expense',status:'paid',amount:45000+i*8000,date:offsetDate(-21-i*3),category:'Taşeron',notes:'',createdAt:now,createdBy:data.settings.person},{id:uid(),projectId:p.id,title:'Zemin etüdü bedeli',type:'expense',status:'planned',amount:22000+i*3000,date:offsetDate(9),category:'Danışmanlık',notes:'',createdAt:now,createdBy:data.settings.person});});
data.activity=[{id:uid(),text:'Örnek çalışma alanı oluşturuldu.',time:new Date().toISOString(),projectId:null}];return data;
}
export function migrate(old){const d=seed();d.projects=[];d.clients=[];d.finance=[];for(const p of old.projects){let c=d.clients.find(c=>c.name===p.client);if(!c){c={id:uid(),name:p.client||'Müşteri',contact:'',email:'',phone:''};d.clients.push(c);}d.projects.push({...p,clientId:c.id,cover:d.projects.length%4,archived:false,sections:p.sections.map(s=>({...s,weight:1,items:s.items.map(o=>({...newItem(d,o.name),...o,workflowId:'documents',stateId:d.workflows[0].states[o.status||0].id,properties:[],files:[],comments:[]}))}))});}d.activity=old.activity||[];return d;}
